// Generated by scripts/generate_frontend_contracts.py from contracts/openapi.json.
export type SchoolProfile = {
  "schema_version": "1.0";
  "school_id": string;
  "name": string;
  "city": "Delhi" | "New Delhi" | "Noida" | "Greater Noida" | "Ghaziabad" | "Gurugram" | "Faridabad";
  "latitude": number;
  "longitude": number;
  "timezone": "Asia/Kolkata";
  "languages": ("en" | "hi")[];
  "is_demo": boolean;
  "updated_at"?: string;
};

export type Health = {
  "status": "ok";
  "service": "hawahawai-backend";
  "environment": string;
  "version": string;
  "phase": 0;
  "timestamp": string;
};

export type Error = {
  "error": {
  "code": string;
  "message": string;
};
};

export type SourceLocation = {
  "latitude": number;
  "longitude": number;
  "station_id": string | null;
  "distance_km": number | null;
};

export type Source = {
  "source_id": string;
  "name": string;
  "url": string;
  "kind": "measurement" | "model_forecast" | "official_order";
  "observed_at": string | null;
  "retrieved_at": string;
  "valid_until": string | null;
  "freshness": "fresh" | "stale" | "unknown";
  "location": SourceLocation | null;
  "limitations": (string)[];
};

export type Aqi = {
  "value": number;
  "scale": "INDIA_AQI" | "US_AQI" | "EUROPEAN_AQI";
  "source_id": string;
  "observed_at": string | null;
  "forecast_for": string | null;
  "source_type": "measurement" | "model_forecast";
};

export type Pollutant = {
  "name": "pm2_5" | "pm10" | "no2" | "o3" | "so2" | "co";
  "value": number;
  "unit": "ug/m3";
  "averaging_period": string;
  "source_id": string;
  "observed_at": string | null;
  "forecast_for": string | null;
  "source_type": "measurement" | "model_forecast";
  "original_unit": string;
};

export type AirReading = {
  "school_id": string;
  "status": "available" | "stale" | "unavailable";
  "aqi": (Aqi)[];
  "pollutants": (Pollutant)[];
  "sources": (Source)[];
  "warnings": (string)[];
  "latitude": number;
  "longitude": number;
  "retrieved_at": string | null;
  "freshness_status": "fresh" | "stale" | "unavailable";
  "data_quality": "modeled_grid_estimate" | "unavailable";
  "cache": {
  "status": "hit" | "miss" | "refreshed" | "stale_fallback";
  "fresh_until": string | null;
};
  "observations": (ForecastPoint)[];
  "observation_providers": (ObservationProvider)[];
  "modeled_current": ForecastPoint | null;
};

export type ForecastPoint = {
  "valid_at": string;
  "aqi": (Aqi)[];
  "pollutants": (Pollutant)[];
};

export type Forecast = {
  "school_id": string;
  "status": "available" | "stale" | "unavailable";
  "generated_at": string | null;
  "points": (ForecastPoint)[];
  "sources": (Source)[];
  "warnings": (string)[];
  "latitude": number;
  "longitude": number;
  "retrieved_at": string | null;
  "freshness_status": "fresh" | "stale" | "unavailable";
  "data_quality": "modeled_grid_estimate" | "unavailable";
  "cache": {
  "status": "hit" | "miss" | "refreshed" | "stale_fallback";
  "fresh_until": string | null;
};
  "horizon_hours": 48;
  "forecast_start": string | null;
  "forecast_end": string | null;
};

export type GrapStatus = {
  "status": "verified" | "VERIFY_STATUS";
  "stage": number | null;
  "effective_from": string | null;
  "verified_at": string | null;
  "order_url": string | null;
  "jurisdiction": string;
  "restrictions": (string)[];
  "sources": (Source)[];
  "active_stage": number | null;
  "verification_state": "VERIFIED_ACTIVE" | "VERIFIED_INACTIVE" | "UNKNOWN" | "STALE" | "CONFLICTING";
  "verification_expires_at": string | null;
  "applicable_restrictions": (Restriction)[];
  "unverified_restrictions": (Restriction)[];
  "source_documents": (RegulatoryDocument)[];
  "snapshot_version": string;
  "schedule_version": string;
  "evaluation_time": string;
  "verification_action_recorded": boolean;
  "next_transition_at": string | null;
  "warnings": (string)[];
};

export type Action = {
  "activity": "assembly" | "sports" | "physical_education" | "other" | "indoor" | "administration" | "parent_communication";
  "instruction": string;
  "rule_ids": (string)[];
  "evidence_ids": (string)[];
  "recommendation": "VERIFY_BEFORE_PROCEEDING" | "NORMAL_WITH_CAVEATS" | "MODIFY" | "INDOOR_ALTERNATIVE" | "ASSESS_INDOOR_ALTERNATIVE" | "VERIFY_STATUS" | "REVIEW_ORDERS" | "HYBRID_CLASSES" | "SUSPEND_OUTDOOR" | "SUSPEND_PHYSICAL_CLASSES" | "REVIEW_ORDER" | "RESCHEDULE_SPORTS" | "AVOID_OUTDOOR_ADVISORY" | "STRUCTURED_REASONS_READY" | "REVIEW_SCHOOL_OPERATIONS" | "FOLLOW_PHYSICAL_CLASS_ORDER";
  "mandatory": boolean;
  "applicable_grades": (number)[];
};

export type Verdict = {
  "school_id": string;
  "status": "decided" | "DATA_INSUFFICIENT" | "VERIFY_STATUS";
  "verdict": "GO_OUTDOORS" | "MODIFIED_OUTDOORS" | "INDOOR_ONLY" | null;
  "generated_at": string;
  "valid_until": string;
  "rule_version": string;
  "rule_ids": (string)[];
  "reasons": (string)[];
  "actions": (Action)[];
  "evidence_ids": (string)[];
  "sources": (Source)[];
  "warnings": (string)[];
  "decision": "GO_OUTDOORS" | "MODIFIED_OUTDOORS" | "INDOOR_ONLY" | "DATA_INSUFFICIENT";
  "evaluation_time": string;
  "policy_version": string;
  "decision_id": string;
  "regulatory_status": GrapStatus;
  "rule_evaluations": (RuleEvaluation)[];
  "evidence": (DecisionEvidence)[];
  "policy_sources": (PolicySource)[];
  "requires_regulatory_verification": boolean;
  "data_quality": {
  "official_observations_available": boolean;
  "station_observations_available": boolean;
  "modeled_data_available": boolean;
  "forecast_available": boolean;
  "current_freshness": string;
  "forecast_freshness": string;
};
  "activity_context": {
  "jurisdiction": "NCT_DELHI";
  "grade": number | null;
  "activity": "all" | "assembly" | "sports" | "physical_education" | "other" | "indoor";
  "window_start": string;
  "window_end": string;
};
  "persistence"?: VerdictPersistence;
};

export type AdvisoryRequest = {
  "verdict_id": string;
  "languages": ("en" | "hi")[];
};

export type Advisory = {
  "school_id": string;
  "verdict_id": string;
  "verdict": "GO_OUTDOORS" | "MODIFIED_OUTDOORS" | "INDOOR_ONLY" | null;
  "generated_at": string;
  "en": string;
  "hi": string;
  "generator": "gemini" | "groq" | "bedrock" | "rule_template";
  "evidence_ids": (string)[];
  "caveats": (string)[];
  "school_name": string;
  "decision": "GO_OUTDOORS" | "MODIFIED_OUTDOORS" | "INDOOR_ONLY" | "DATA_INSUFFICIENT";
  "valid_until": string;
  "languages": ["en", "hi"];
  "explanation_method": "AI" | "DETERMINISTIC";
  "explanation_version": string;
  "generation_scope": "approved_statement_ordering";
  "statement_ids": (string)[];
  "authoritative_decision": Verdict;
  "actions": (LocalizedAction)[];
  "evidence": (DecisionEvidence)[];
  "sources": (Source | PolicySource | RegulatoryDocument)[];
  "regulatory_status": GrapStatus;
  "data_quality": {
  "official_observations_available": boolean;
  "station_observations_available": boolean;
  "modeled_data_available": boolean;
  "forecast_available": boolean;
  "current_freshness": string;
  "forecast_freshness": string;
};
  "cache": {
  "status": "hit" | "miss";
};
  "observations": (DecisionEvidence)[];
  "modeled_conditions": (DecisionEvidence)[];
  "forecast_summary": {
  "scope": string;
  "points": (DecisionEvidence)[];
  "available": boolean;
};
};

export type ObservationProvider = {
  "observations": (ForecastPoint)[];
  "status": "unavailable";
  "source_name": string;
  "source_type": "measurement";
  "source_url": string;
  "retrieved_at": string;
  "warnings": (string)[];
};

export type RegulatoryDocument = {
  "document_id": string;
  "title": string;
  "authority": string;
  "url": string;
  "published_on": string;
  "document_type": "SCHEDULE" | "ACTIVATION" | "REVOCATION" | "SCHOOL_ORDER" | "ADVISORY" | "PRESS_RELEASE";
  "access_status": "RESEARCHED" | "UNAVAILABLE" | "HUMAN_REVIEWED";
  "sha256": string | null;
  "effective_from": string | null;
  "effective_until": string | null;
  "verification_status": "HUMAN_REVIEWED" | "UNVERIFIED";
};

export type Restriction = {
  "restriction_id": string;
  "document_id": string;
  "clause": string;
  "jurisdiction": "NCT_DELHI";
  "grades": (number)[];
  "activity": "all" | "assembly" | "sports" | "physical_education" | "other" | "administration";
  "action": "HYBRID_CLASSES" | "SUSPEND_OUTDOOR" | "SUSPEND_PHYSICAL_CLASSES" | "REVIEW_ORDER" | "RESCHEDULE_SPORTS" | "AVOID_OUTDOOR_ADVISORY";
  "mandatory": boolean;
  "effective_from": string;
  "effective_until": string | null;
  "minimum_stage": number | null;
  "revoked_by": string | null;
};

export type RuleEvaluation = {
  "rule_id": string;
  "priority": number;
  "message": string;
  "evidence_ids": (string)[];
};

export type DecisionEvidence = {
  "evidence_id": string;
  "kind": "station_observation" | "modeled_current" | "activity_forecast";
  "freshness": "fresh";
  "value": number;
  "scale": "US_AQI";
  "source_id": string;
  "source_type": "measurement" | "model_forecast";
  "timestamp": string;
  "pollutants": (Pollutant)[];
  "station_location": SourceLocation | null;
};

export type PolicySource = {
  "evidence_id": string;
  "title": string;
  "url": string;
  "authority": string;
  "published_on": string | null;
  "scope": string;
};

export type VerdictPersistence = {
  "status": "stored" | "reused" | "repaired" | "unavailable" | "corrupt" | "busy";
  "storage_version": "verdict-record-v1";
  "record_id": string | null;
  "historical": false;
};

export type VerdictRecord = {
  "storage_version": "verdict-record-v1";
  "school_id": "delhi-demo-school";
  "record_id": string;
  "profile_fingerprint": string;
  "semantic_fingerprint": string;
  "context": {
  "jurisdiction": "NCT_DELHI";
  "grade": number | null;
  "activity": "all" | "assembly" | "sports" | "physical_education" | "other" | "indoor";
};
  "local_date": string;
  "origin": "ON_DEMAND" | "SCHEDULED";
  "decision": Verdict;
  "created_at": string;
};

export type VerdictHistory = {
  "school_id": string;
  "status": "historical";
  "actionable": false;
  "retrieved_at": string;
  "expired": boolean;
  "matches_current_profile": boolean;
  "record": VerdictRecord;
};

export type LocalizedAction = {
  "activity": "assembly" | "sports" | "physical_education" | "other" | "indoor" | "administration" | "parent_communication";
  "instruction": string;
  "rule_ids": (string)[];
  "evidence_ids": (string)[];
  "recommendation": "VERIFY_BEFORE_PROCEEDING" | "NORMAL_WITH_CAVEATS" | "MODIFY" | "INDOOR_ALTERNATIVE" | "ASSESS_INDOOR_ALTERNATIVE" | "VERIFY_STATUS" | "REVIEW_ORDERS" | "HYBRID_CLASSES" | "SUSPEND_OUTDOOR" | "SUSPEND_PHYSICAL_CLASSES" | "REVIEW_ORDER" | "RESCHEDULE_SPORTS" | "AVOID_OUTDOOR_ADVISORY" | "STRUCTURED_REASONS_READY" | "REVIEW_SCHOOL_OPERATIONS" | "FOLLOW_PHYSICAL_CLASS_ORDER";
  "mandatory": boolean;
  "applicable_grades": (number)[];
  "en": string;
  "hi": string;
};
