"""Generate browser types from the existing OpenAPI authority; no schema changes."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
schemas = json.loads((ROOT / 'contracts/openapi.json').read_text())['components']['schemas']


def ts(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    if 'const' in schema:
        return json.dumps(schema['const']) if not isinstance(schema['const'], list) else '[' + ', '.join(json.dumps(v) for v in schema['const']) + ']'
    if 'enum' in schema:
        return ' | '.join(json.dumps(v) for v in schema['enum'])
    if 'anyOf' in schema:
        return ' | '.join(ts(s) for s in schema['anyOf'])
    kind = schema.get('type')
    if kind == 'array':
        return '(' + ts(schema['items']) + ')[]'
    if kind == 'object':
        required = schema.get('required', [])
        return '{\n' + '\n'.join('  ' + json.dumps(k) + ('' if k in required else '?') + ': ' + ts(v) + ';' for k, v in schema.get('properties', {}).items()) + '\n}'
    return {'string': 'string', 'number': 'number', 'integer': 'number', 'boolean': 'boolean', 'null': 'null'}.get(kind, 'unknown')


output = '// Generated by scripts/generate_frontend_contracts.py from contracts/openapi.json.\n'
output += '\n\n'.join('export type ' + name + ' = ' + ts(schema) + ';' for name, schema in schemas.items()) + '\n'
target = ROOT / 'frontend/src/contracts.ts'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if args.check:
    assert target.read_text(encoding='utf-8') == output, 'Frontend contract types are stale'
    print('PASS: frontend types match existing OpenAPI')
else:
    target.write_text(output, encoding='utf-8')
    print('Generated frontend contract types')
